# Generated by Django 4.2.4 on 2023-08-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appToDo', '0004_remove_usuario_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='harry', max_length=200),
            preserve_default=False,
        ),
    ]
