# Generated by Django 4.2.4 on 2023-08-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appToDo', '0005_usuario_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
