# Generated by Django 4.2.4 on 2023-08-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appToDo', '0006_alter_tarea_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(default='Tarea de colegio'),
            preserve_default=False,
        ),
    ]
